ASSETS = {
    "action_connected": ("assets/bin/action/connected_24x24.bin", 24, 24),
    "action_delete": ("assets/bin/action/delete_24x24.bin", 24, 24),
    "action_disconnected": ("assets/bin/action/disconnected_24x24.bin", 24, 24),
    "action_info": ("assets/bin/action/info_24x24.bin", 24, 24),
    "action_keyboard": ("assets/bin/action/keyboard_24x24.bin", 24, 24),
    "action_plus_add": ("assets/bin/action/plus_add_24x24.bin", 24, 24),
    "action_power": ("assets/bin/action/power_24x24.bin", 24, 24),
    "action_question": ("assets/bin/action/question_24x24.bin", 24, 24),
    "action_refresh_scan": ("assets/bin/action/refresh_scan_24x24.bin", 24, 24),
    "action_scroll": ("assets/bin/action/scroll_24x24.bin", 24, 24),
    "menu_account": ("assets/bin/menu/account_24x24.bin", 24, 24),
    "menu_device": ("assets/bin/menu/device_24x24.bin", 24, 24),
    "menu_graphics": ("assets/bin/menu/graphics_24x24.bin", 24, 24),
    "menu_home": ("assets/bin/menu/home_24x24.bin", 24, 24),
    "menu_messages": ("assets/bin/menu/messages_24x24.bin", 24, 24),
    "menu_messages_selected": ("assets/bin/menu/messages_selected_24x24.bin", 24, 24),
    "menu_presets": ("assets/bin/menu/presets_24x24.bin", 24, 24),
    "menu_presets_selected": ("assets/bin/menu/presets_selected_24x24.bin", 24, 24),
    "menu_settings": ("assets/bin/menu/settings_24x24.bin", 24, 24),
    "menu_settings_selected": ("assets/bin/menu/settings_selected_24x24.bin", 24, 24),
    "menu_wifi": ("assets/bin/menu/wifi_24x24.bin", 24, 24),
    "nav_back": ("assets/bin/navigation/back_24x24.bin", 24, 24),
    "nav_change_edit": ("assets/bin/navigation/change_edit_24x24.bin", 24, 24),
    "nav_enter_select": ("assets/bin/navigation/enter_select_24x24.bin", 24, 24),
    "nav_send": ("assets/bin/navigation/send_24x24.bin", 24, 24),
    "state_device_error": ("assets/bin/state/device_error_64x64.bin", 64, 64),
    "state_generic_error": ("assets/bin/state/generic_error_64x64.bin", 64, 64),
    "state_http_error": ("assets/bin/state/http_error_64x64.bin", 64, 64),
    "state_loading_message": ("assets/bin/state/loading_message_64x64.bin", 64, 64),
    "state_loading_presets": ("assets/bin/state/loading_presets_64x64.bin", 64, 64),
    "state_sending": ("assets/bin/state/sending_64x64.bin", 64, 64),
    "state_software_error": ("assets/bin/state/software_error_64x64.bin", 64, 64),
    "state_success": ("assets/bin/state/success_64x64.bin", 64, 64),
    "state_wifi_error": ("assets/bin/state/wifi_error_64x64.bin", 64, 64),
    "state_wifi_success": ("assets/bin/state/wifi_success_64x64.bin", 64, 64),
    "status_alert": ("assets/bin/status/alert_16x16.bin", 16, 16),
    "status_battery": ("assets/bin/status/battery_16x16.bin", 16, 16),
    "status_lock": ("assets/bin/status/lock_16x16.bin", 16, 16),
    "status_sync": ("assets/bin/status/sync_16x16.bin", 16, 16),
    "status_wifi_0": ("assets/bin/status/wifi_0_16x16.bin", 16, 16),
    "status_wifi_1": ("assets/bin/status/wifi_1_16x16.bin", 16, 16),
    "status_wifi_2": ("assets/bin/status/wifi_2_16x16.bin", 16, 16),
    "status_wifi_3": ("assets/bin/status/wifi_3_16x16.bin", 16, 16),
    "status_wifi_4": ("assets/bin/status/wifi_4_16x16.bin", 16, 16),
    "status_wifi_error": ("assets/bin/status/wifi_error_16x16.bin", 16, 16),
}


ICONS = {
    "menu": {
        "home": "menu_home",
        "messages": "menu_messages",
        "messages_selected": "menu_messages_selected",
        "presets": "menu_presets",
        "presets_selected": "menu_presets_selected",
        "settings": "menu_settings",
        "settings_selected": "menu_settings_selected",
        "account": "menu_account",
        "device": "menu_device",
        "wifi": "menu_wifi",
        "graphics": "menu_graphics",
    },
    "navigation": {
        "back": "nav_back",
        "edit": "nav_change_edit",
        "select": "nav_enter_select",
        "send": "nav_send",
    },
    "action": {
        "connected": "action_connected",
        "disconnected": "action_disconnected",
        "delete": "action_delete",
        "info": "action_info",
        "keyboard": "action_keyboard",
        "add": "action_plus_add",
        "power": "action_power",
        "question": "action_question",
        "refresh": "action_refresh_scan",
        "scroll": "action_scroll",
    },
    "status": {
        "alert": "status_alert",
        "battery": "status_battery",
        "lock": "status_lock",
        "sync": "status_sync",
        "wifi_0": "status_wifi_0",
        "wifi_1": "status_wifi_1",
        "wifi_2": "status_wifi_2",
        "wifi_3": "status_wifi_3",
        "wifi_4": "status_wifi_4",
        "wifi_error": "status_wifi_error",
    },
    "state": {
        "loading_message": "state_loading_message",
        "loading_presets": "state_loading_presets",
        "sending": "state_sending",
        "success": "state_success",
        "http_error": "state_http_error",
        "device_error": "state_device_error",
        "software_error": "state_software_error",
        "wifi_error": "state_wifi_error",
        "wifi_success": "state_wifi_success",
        "generic_error": "state_generic_error",
    },
}


def icon(category, name):
    return ICONS[category][name]


REGIONS = {
    "status": (0, 0, 240, 24),
    "title": (0, 24, 240, 32),
    "content": (0, 56, 240, 224),
    "nav": (0, 280, 240, 40),
}


PLACEMENTS = (
    ("home", "menu_messages", 20, 78, "content"),
    ("home", "menu_presets", 20, 126, "content"),
    ("home", "menu_settings", 20, 174, "content"),
    ("home", "action_scroll", 48, 288, "nav"),
    ("home", "nav_enter_select", 168, 288, "nav"),
    ("loading_messages", "state_loading_message", 88, 96, "content"),
    ("loading_presets", "state_loading_presets", 88, 96, "content"),
    ("sending", "state_sending", 88, 96, "content"),
    ("notification", "state_success", 88, 96, "content"),
    ("notification", "nav_enter_select", 108, 288, "nav"),
    ("error_http", "state_http_error", 88, 96, "content"),
    ("error_http", "nav_enter_select", 108, 288, "nav"),
    ("error_device", "state_device_error", 88, 96, "content"),
    ("error_device", "nav_enter_select", 108, 288, "nav"),
    ("error_software", "state_software_error", 88, 96, "content"),
    ("error_software", "nav_enter_select", 108, 288, "nav"),
    ("error_wifi", "state_wifi_error", 88, 96, "content"),
    ("error_wifi", "nav_enter_select", 108, 288, "nav"),
    ("error_generic", "state_generic_error", 88, 96, "content"),
    ("error_generic", "nav_enter_select", 108, 288, "nav"),
    ("settings", "menu_account", 20, 78, "content"),
    ("settings", "menu_device", 20, 126, "content"),
    ("settings", "menu_wifi", 20, 174, "content"),
    ("settings", "menu_graphics", 20, 222, "content"),
    ("settings_about", "action_question", 20, 222, "content"),
    ("settings_actions", "nav_back", 48, 288, "nav"),
    ("settings_actions", "nav_change_edit", 168, 288, "nav"),
    ("preset_menu", "action_scroll", 48, 288, "nav"),
    ("preset_menu", "nav_enter_select", 168, 288, "nav"),
    ("preset_actions", "nav_back", 48, 288, "nav"),
    ("preset_actions", "nav_send", 168, 288, "nav"),
    ("wifi_status", "status_wifi_4", 216, 4, "status"),
    ("wifi_status", "state_wifi_success", 88, 96, "content"),
    ("wifi_status", "nav_back", 48, 288, "nav"),
    ("wifi_status", "nav_change_edit", 168, 288, "nav"),
    ("wifi_offline", "status_wifi_error", 216, 4, "status"),
    ("wifi_offline", "state_wifi_error", 88, 96, "content"),
    ("wifi_scanning", "status_sync", 196, 4, "status"),
    ("wifi_scanning", "status_wifi_0", 216, 4, "status"),
    ("wifi_list", "status_wifi_4", 176, 68, "content"),
    ("wifi_list", "status_lock", 152, 68, "content"),
    ("wifi_list", "status_wifi_3", 176, 108, "content"),
    ("wifi_list", "status_lock", 152, 108, "content"),
    ("wifi_list", "status_wifi_2", 176, 148, "content"),
    ("wifi_list", "status_lock", 152, 148, "content"),
    ("wifi_list", "status_wifi_1", 176, 188, "content"),
    ("wifi_list", "status_lock", 152, 188, "content"),
    ("wifi_list", "status_wifi_0", 176, 228, "content"),
    ("wifi_list", "status_lock", 152, 228, "content"),
    ("wifi_list_actions", "nav_back", 48, 288, "nav"),
    ("wifi_list_actions", "nav_enter_select", 168, 288, "nav"),
    ("wifi_connecting", "status_sync", 216, 4, "status"),
    ("wifi_success", "status_wifi_4", 216, 4, "status"),
    ("wifi_success", "state_wifi_success", 88, 96, "content"),
    ("wifi_failure", "status_wifi_error", 216, 4, "status"),
    ("wifi_failure", "state_wifi_error", 88, 96, "content"),
    ("keyboard", "action_scroll", 28, 288, "nav"),
    ("keyboard", "nav_change_edit", 108, 288, "nav"),
    ("keyboard", "nav_enter_select", 188, 288, "nav"),
)


def asset(name):
    try:
        return ASSETS[name]
    except KeyError:
        raise KeyError("unknown asset: " + str(name))
